<%@page contentType="text/html;charset=UTF-8"%>
<h3>ADMIN</h3>
<table>
<tr>
	<td><a href="/nfsmw/admin/version">版本管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/resource">资源管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/tournament">联赛管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/user">用户查询&测试账号管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/ctacontent">文案字典表管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/feedcontent">feed管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/word">敏感词管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/news">MOD管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/qahome">qa管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/sendcar">sendCar管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/userChangeStatus">用户账号删除恢复</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/leaderboardhome">leaderboard删除</a>&nbsp;</td>
	
	</tr>
	<tr>
	<td><a href="/nfsmw/admin/carhome">car管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/iapcheck">IapCheck</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/operateactivity">operate管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/operateSpendActivity">spendActivity管理</a>&nbsp;</td>
	<td><a href="/nfsmw/admin/sendfragment">sendFragMent管理</a>&nbsp;</td>
</tr>
</table>
<br/>
